/**
 * Expand Common Words List
 * 
 * Expands the word list from 150 to 1,000+ words using frequency data.
 * This is a quick expansion script to add more common Spanish words.
 * 
 * Usage:
 *   npx tsx scripts/expand-word-list.ts --target 1000
 */

import * as fs from 'fs';
import * as path from 'path';

const WORDS_FILE = path.join(__dirname, 'common-words-5000.json');

// Common Spanish words by frequency (151-500)
// Curated from Spanish frequency corpus data
// Goal: Add ~350 words to reach 500 total (90 minutes of generation)
const additionalWords = [
  // High-frequency verbs
  { word: 'seguir', pos: 'verb', translation: 'to follow/continue', frequency: 'very_high' },
  { word: 'comenzar', pos: 'verb', translation: 'to begin', frequency: 'very_high' },
  { word: 'partir', pos: 'verb', translation: 'to leave/depart', frequency: 'very_high' },
  { word: 'caer', pos: 'verb', translation: 'to fall', frequency: 'very_high' },
  { word: 'presentar', pos: 'verb', translation: 'to present', frequency: 'very_high' },
  { word: 'crear', pos: 'verb', translation: 'to create', frequency: 'very_high' },
  { word: 'abrir', pos: 'verb', translation: 'to open', frequency: 'very_high' },
  { word: 'considerar', pos: 'verb', translation: 'to consider', frequency: 'very_high' },
  { word: 'oír', pos: 'verb', translation: 'to hear', frequency: 'very_high' },
  { word: 'acabar', pos: 'verb', translation: 'to finish', frequency: 'very_high' },
  { word: 'permitir', pos: 'verb', translation: 'to permit/allow', frequency: 'very_high' },
  { word: 'aparecer', pos: 'verb', translation: 'to appear', frequency: 'very_high' },
  { word: 'conseguir', pos: 'verb', translation: 'to get/obtain', frequency: 'very_high' },
  { word: 'servir', pos: 'verb', translation: 'to serve', frequency: 'very_high' },
  { word: 'sacar', pos: 'verb', translation: 'to take out', frequency: 'very_high' },
  { word: 'necesitar', pos: 'verb', translation: 'to need', frequency: 'very_high' },
  { word: 'mantener', pos: 'verb', translation: 'to maintain', frequency: 'very_high' },
  { word: 'resultar', pos: 'verb', translation: 'to result/turn out', frequency: 'very_high' },
  { word: 'leer', pos: 'verb', translation: 'to read', frequency: 'very_high' },
  { word: 'ofrecer', pos: 'verb', translation: 'to offer', frequency: 'very_high' },
  { word: 'tocar', pos: 'verb', translation: 'to touch/play', frequency: 'very_high' },
  { word: 'reconocer', pos: 'verb', translation: 'to recognize', frequency: 'very_high' },
  { word: 'estudiar', pos: 'verb', translation: 'to study', frequency: 'very_high' },
  { word: 'alcanzar', pos: 'verb', translation: 'to reach/achieve', frequency: 'very_high' },
  { word: 'nacer', pos: 'verb', translation: 'to be born', frequency: 'very_high' },
  { word: 'dirigir', pos: 'verb', translation: 'to direct', frequency: 'very_high' },
  { word: 'correr', pos: 'verb', translation: 'to run', frequency: 'very_high' },
  { word: 'utilizar', pos: 'verb', translation: 'to use/utilize', frequency: 'very_high' },
  { word: 'pagar', pos: 'verb', translation: 'to pay', frequency: 'very_high' },
  { word: 'ayudar', pos: 'verb', translation: 'to help', frequency: 'very_high' },
  { word: 'gustar', pos: 'verb', translation: 'to like/be pleasing', frequency: 'very_high' },
  { word: 'jugar', pos: 'verb', translation: 'to play', frequency: 'very_high' },
  { word: 'realizar', pos: 'verb', translation: 'to carry out', frequency: 'very_high' },
  { word: 'intentar', pos: 'verb', translation: 'to try/attempt', frequency: 'very_high' },
  { word: 'subir', pos: 'verb', translation: 'to go up/climb', frequency: 'very_high' },
  { word: 'bajar', pos: 'verb', translation: 'to go down/lower', frequency: 'very_high' },
  { word: 'cumplir', pos: 'verb', translation: 'to fulfill/turn (age)', frequency: 'very_high' },
  { word: 'echar', pos: 'verb', translation: 'to throw', frequency: 'very_high' },
  { word: 'andar', pos: 'verb', translation: 'to walk', frequency: 'very_high' },
  { word: 'responder', pos: 'verb', translation: 'to respond', frequency: 'very_high' },
  
  // Body parts & people
  { word: 'persona', pos: 'noun', translation: 'person', frequency: 'very_high' },
  { word: 'gente', pos: 'noun', translation: 'people', frequency: 'very_high' },
  { word: 'cabeza', pos: 'noun', translation: 'head', frequency: 'very_high' },
  { word: 'cuerpo', pos: 'noun', translation: 'body', frequency: 'very_high' },
  { word: 'lado', pos: 'noun', translation: 'side', frequency: 'very_high' },
  { word: 'pie', pos: 'noun', translation: 'foot', frequency: 'very_high' },
  { word: 'frente', pos: 'noun', translation: 'front/forehead', frequency: 'very_high' },
  { word: 'brazo', pos: 'noun', translation: 'arm', frequency: 'very_high' },
  { word: 'boca', pos: 'noun', translation: 'mouth', frequency: 'very_high' },
  { word: 'cara', pos: 'noun', translation: 'face', frequency: 'very_high' },
  { word: 'corazón', pos: 'noun', translation: 'heart', frequency: 'very_high' },
  { word: 'dedo', pos: 'noun', translation: 'finger', frequency: 'very_high' },
  { word: 'espalda', pos: 'noun', translation: 'back', frequency: 'very_high' },
  { word: 'pierna', pos: 'noun', translation: 'leg', frequency: 'very_high' },
  { word: 'rodilla', pos: 'noun', translation: 'knee', frequency: 'high' },
  { word: 'oreja', pos: 'noun', translation: 'ear', frequency: 'high' },
  { word: 'nariz', pos: 'noun', translation: 'nose', frequency: 'high' },
  { word: 'lengua', pos: 'noun', translation: 'tongue/language', frequency: 'very_high' },
  { word: 'voz', pos: 'noun', translation: 'voice', frequency: 'very_high' },
  { word: 'pelo', pos: 'noun', translation: 'hair', frequency: 'high' },
  
  // Family & relationships
  { word: 'amigo', pos: 'noun', translation: 'friend', frequency: 'very_high' },
  { word: 'compañero', pos: 'noun', translation: 'companion/partner', frequency: 'very_high' },
  { word: 'hermano', pos: 'noun', translation: 'brother', frequency: 'very_high' },
  { word: 'hermana', pos: 'noun', translation: 'sister', frequency: 'very_high' },
  { word: 'esposo', pos: 'noun', translation: 'husband', frequency: 'very_high' },
  { word: 'esposa', pos: 'noun', translation: 'wife', frequency: 'very_high' },
  { word: 'abuelo', pos: 'noun', translation: 'grandfather', frequency: 'high' },
  { word: 'abuela', pos: 'noun', translation: 'grandmother', frequency: 'high' },
  { word: 'tío', pos: 'noun', translation: 'uncle', frequency: 'high' },
  { word: 'tía', pos: 'noun', translation: 'aunt', frequency: 'high' },
  { word: 'primo', pos: 'noun', translation: 'cousin', frequency: 'high' },
  { word: 'novio', pos: 'noun', translation: 'boyfriend/groom', frequency: 'high' },
  { word: 'novia', pos: 'noun', translation: 'girlfriend/bride', frequency: 'high' },
  { word: 'bebé', pos: 'noun', translation: 'baby', frequency: 'high' },
  
  // Time & nature
  { word: 'luz', pos: 'noun', translation: 'light', frequency: 'very_high' },
  { word: 'noche', pos: 'noun', translation: 'night', frequency: 'very_high' },
  { word: 'sol', pos: 'noun', translation: 'sun', frequency: 'very_high' },
  { word: 'aire', pos: 'noun', translation: 'air', frequency: 'very_high' },
  { word: 'mar', pos: 'noun', translation: 'sea', frequency: 'very_high' },
  { word: 'cielo', pos: 'noun', translation: 'sky/heaven', frequency: 'very_high' },
  { word: 'luna', pos: 'noun', translation: 'moon', frequency: 'very_high' },
  { word: 'estrella', pos: 'noun', translation: 'star', frequency: 'very_high' },
  { word: 'nube', pos: 'noun', translation: 'cloud', frequency: 'high' },
  { word: 'viento', pos: 'noun', translation: 'wind', frequency: 'high' },
  { word: 'lluvia', pos: 'noun', translation: 'rain', frequency: 'high' },
  { word: 'nieve', pos: 'noun', translation: 'snow', frequency: 'high' },
  { word: 'fuego', pos: 'noun', translation: 'fire', frequency: 'very_high' },
  { word: 'árbol', pos: 'noun', translation: 'tree', frequency: 'very_high' },
  { word: 'flor', pos: 'noun', translation: 'flower', frequency: 'high' },
  { word: 'río', pos: 'noun', translation: 'river', frequency: 'very_high' },
  { word: 'montaña', pos: 'noun', translation: 'mountain', frequency: 'high' },
  { word: 'playa', pos: 'noun', translation: 'beach', frequency: 'high' },
  { word: 'bosque', pos: 'noun', translation: 'forest', frequency: 'high' },
  { word: 'campo', pos: 'noun', translation: 'field/countryside', frequency: 'very_high' },
  
  // Abstract concepts
  { word: 'amor', pos: 'noun', translation: 'love', frequency: 'very_high' },
  { word: 'paz', pos: 'noun', translation: 'peace', frequency: 'very_high' },
  { word: 'fuerza', pos: 'noun', translation: 'strength/force', frequency: 'very_high' },
  { word: 'ley', pos: 'noun', translation: 'law', frequency: 'very_high' },
  { word: 'sangre', pos: 'noun', translation: 'blood', frequency: 'very_high' },
  { word: 'arte', pos: 'noun', translation: 'art', frequency: 'very_high' },
  { word: 'papel', pos: 'noun', translation: 'paper/role', frequency: 'very_high' },
  { word: 'música', pos: 'noun', translation: 'music', frequency: 'very_high' },
  { word: 'verdad', pos: 'noun', translation: 'truth', frequency: 'very_high' },
  { word: 'mentira', pos: 'noun', translation: 'lie', frequency: 'high' },
  { word: 'suerte', pos: 'noun', translation: 'luck', frequency: 'very_high' },
  { word: 'miedo', pos: 'noun', translation: 'fear', frequency: 'very_high' },
  { word: 'alegría', pos: 'noun', translation: 'joy', frequency: 'high' },
  { word: 'tristeza', pos: 'noun', translation: 'sadness', frequency: 'high' },
  { word: 'esperanza', pos: 'noun', translation: 'hope', frequency: 'very_high' },
  { word: 'sueño', pos: 'noun', translation: 'dream/sleep', frequency: 'very_high' },
  { word: 'pensamiento', pos: 'noun', translation: 'thought', frequency: 'high' },
  { word: 'sentimiento', pos: 'noun', translation: 'feeling', frequency: 'high' },
  { word: 'razón', pos: 'noun', translation: 'reason', frequency: 'very_high' },
  { word: 'mente', pos: 'noun', translation: 'mind', frequency: 'very_high' },
  
  // Common objects & places
  { word: 'cama', pos: 'noun', translation: 'bed', frequency: 'very_high' },
  { word: 'silla', pos: 'noun', translation: 'chair', frequency: 'very_high' },
  { word: 'mesa', pos: 'noun', translation: 'table', frequency: 'very_high' },
  { word: 'puerta', pos: 'noun', translation: 'door', frequency: 'very_high' },
  { word: 'ventana', pos: 'noun', translation: 'window', frequency: 'very_high' },
  { word: 'pared', pos: 'noun', translation: 'wall', frequency: 'very_high' },
  { word: 'suelo', pos: 'noun', translation: 'floor/ground', frequency: 'very_high' },
  { word: 'techo', pos: 'noun', translation: 'roof/ceiling', frequency: 'high' },
  { word: 'cocina', pos: 'noun', translation: 'kitchen', frequency: 'high' },
  { word: 'baño', pos: 'noun', translation: 'bathroom', frequency: 'high' },
  { word: 'habitación', pos: 'noun', translation: 'room', frequency: 'very_high' },
  { word: 'edificio', pos: 'noun', translation: 'building', frequency: 'very_high' },
  { word: 'tienda', pos: 'noun', translation: 'store/shop', frequency: 'very_high' },
  { word: 'mercado', pos: 'noun', translation: 'market', frequency: 'high' },
  { word: 'restaurante', pos: 'noun', translation: 'restaurant', frequency: 'high' },
  { word: 'hotel', pos: 'noun', translation: 'hotel', frequency: 'high' },
  { word: 'hospital', pos: 'noun', translation: 'hospital', frequency: 'very_high' },
  { word: 'iglesia', pos: 'noun', translation: 'church', frequency: 'very_high' },
  { word: 'banco', pos: 'noun', translation: 'bank/bench', frequency: 'very_high' },
  { word: 'oficina', pos: 'noun', translation: 'office', frequency: 'very_high' },
  
  // Food & drink
  { word: 'comida', pos: 'noun', translation: 'food', frequency: 'very_high' },
  { word: 'bebida', pos: 'noun', translation: 'drink', frequency: 'high' },
  { word: 'pan', pos: 'noun', translation: 'bread', frequency: 'very_high' },
  { word: 'leche', pos: 'noun', translation: 'milk', frequency: 'high' },
  { word: 'café', pos: 'noun', translation: 'coffee', frequency: 'very_high' },
  { word: 'té', pos: 'noun', translation: 'tea', frequency: 'high' },
  { word: 'vino', pos: 'noun', translation: 'wine', frequency: 'very_high' },
  { word: 'carne', pos: 'noun', translation: 'meat', frequency: 'very_high' },
  { word: 'pescado', pos: 'noun', translation: 'fish', frequency: 'high' },
  { word: 'pollo', pos: 'noun', translation: 'chicken', frequency: 'high' },
  { word: 'huevo', pos: 'noun', translation: 'egg', frequency: 'high' },
  { word: 'arroz', pos: 'noun', translation: 'rice', frequency: 'high' },
  { word: 'fruta', pos: 'noun', translation: 'fruit', frequency: 'high' },
  { word: 'verdura', pos: 'noun', translation: 'vegetable', frequency: 'high' },
  { word: 'queso', pos: 'noun', translation: 'cheese', frequency: 'high' },
  { word: 'sal', pos: 'noun', translation: 'salt', frequency: 'high' },
  { word: 'azúcar', pos: 'noun', translation: 'sugar', frequency: 'high' },
  
  // Colors & adjectives
  { word: 'blanco', pos: 'adjective', translation: 'white', frequency: 'very_high' },
  { word: 'negro', pos: 'adjective', translation: 'black', frequency: 'very_high' },
  { word: 'rojo', pos: 'adjective', translation: 'red', frequency: 'very_high' },
  { word: 'azul', pos: 'adjective', translation: 'blue', frequency: 'very_high' },
  { word: 'verde', pos: 'adjective', translation: 'green', frequency: 'very_high' },
  { word: 'amarillo', pos: 'adjective', translation: 'yellow', frequency: 'very_high' },
  { word: 'gris', pos: 'adjective', translation: 'gray', frequency: 'high' },
  { word: 'marrón', pos: 'adjective', translation: 'brown', frequency: 'high' },
  { word: 'rosa', pos: 'adjective', translation: 'pink', frequency: 'high' },
  { word: 'morado', pos: 'adjective', translation: 'purple', frequency: 'high' },
  
  // Common adjectives
  { word: 'fuerte', pos: 'adjective', translation: 'strong', frequency: 'very_high' },
  { word: 'débil', pos: 'adjective', translation: 'weak', frequency: 'very_high' },
  { word: 'feliz', pos: 'adjective', translation: 'happy', frequency: 'very_high' },
  { word: 'triste', pos: 'adjective', translation: 'sad', frequency: 'very_high' },
  { word: 'rico', pos: 'adjective', translation: 'rich', frequency: 'very_high' },
  { word: 'pobre', pos: 'adjective', translation: 'poor', frequency: 'very_high' },
  { word: 'lleno', pos: 'adjective', translation: 'full', frequency: 'very_high' },
  { word: 'vacío', pos: 'adjective', translation: 'empty', frequency: 'very_high' },
  { word: 'cerca', pos: 'adverb', translation: 'near/close', frequency: 'very_high' },
  { word: 'lejos', pos: 'adverb', translation: 'far', frequency: 'very_high' },
  { word: 'rápido', pos: 'adjective', translation: 'fast', frequency: 'very_high' },
  { word: 'lento', pos: 'adjective', translation: 'slow', frequency: 'high' },
  { word: 'fácil', pos: 'adjective', translation: 'easy', frequency: 'very_high' },
  { word: 'difícil', pos: 'adjective', translation: 'difficult', frequency: 'very_high' },
  { word: 'importante', pos: 'adjective', translation: 'important', frequency: 'very_high' },
  { word: 'necesario', pos: 'adjective', translation: 'necessary', frequency: 'very_high' },
  { word: 'posible', pos: 'adjective', translation: 'possible', frequency: 'very_high' },
  { word: 'imposible', pos: 'adjective', translation: 'impossible', frequency: 'very_high' },
  { word: 'verdadero', pos: 'adjective', translation: 'true', frequency: 'very_high' },
  { word: 'falso', pos: 'adjective', translation: 'false', frequency: 'high' },
  { word: 'simple', pos: 'adjective', translation: 'simple', frequency: 'very_high' },
  { word: 'complejo', pos: 'adjective', translation: 'complex', frequency: 'high' },
  { word: 'limpio', pos: 'adjective', translation: 'clean', frequency: 'high' },
  { word: 'sucio', pos: 'adjective', translation: 'dirty', frequency: 'high' },
  { word: 'caliente', pos: 'adjective', translation: 'hot', frequency: 'very_high' },
  { word: 'frío', pos: 'adjective', translation: 'cold', frequency: 'very_high' },
  { word: 'alto', pos: 'adjective', translation: 'tall/high', frequency: 'very_high' },
  { word: 'bajo', pos: 'adjective', translation: 'short/low', frequency: 'very_high' },
  { word: 'ancho', pos: 'adjective', translation: 'wide', frequency: 'high' },
  { word: 'estrecho', pos: 'adjective', translation: 'narrow', frequency: 'high' },
  { word: 'gordo', pos: 'adjective', translation: 'fat', frequency: 'high' },
  { word: 'delgado', pos: 'adjective', translation: 'thin/slim', frequency: 'high' },
  { word: 'hermoso', pos: 'adjective', translation: 'beautiful', frequency: 'very_high' },
  { word: 'feo', pos: 'adjective', translation: 'ugly', frequency: 'high' },
  { word: 'duro', pos: 'adjective', translation: 'hard', frequency: 'very_high' },
  { word: 'blando', pos: 'adjective', translation: 'soft', frequency: 'high' },
  { word: 'seco', pos: 'adjective', translation: 'dry', frequency: 'high' },
  { word: 'mojado', pos: 'adjective', translation: 'wet', frequency: 'high' },
  { word: 'abierto', pos: 'adjective', translation: 'open', frequency: 'very_high' },
  { word: 'cerrado', pos: 'adjective', translation: 'closed', frequency: 'very_high' },
  
  // Numbers & quantities
  { word: 'uno', pos: 'number', translation: 'one', frequency: 'very_high' },
  { word: 'dos', pos: 'number', translation: 'two', frequency: 'very_high' },
  { word: 'tres', pos: 'number', translation: 'three', frequency: 'very_high' },
  { word: 'cuatro', pos: 'number', translation: 'four', frequency: 'very_high' },
  { word: 'cinco', pos: 'number', translation: 'five', frequency: 'very_high' },
  { word: 'seis', pos: 'number', translation: 'six', frequency: 'very_high' },
  { word: 'siete', pos: 'number', translation: 'seven', frequency: 'very_high' },
  { word: 'ocho', pos: 'number', translation: 'eight', frequency: 'very_high' },
  { word: 'nueve', pos: 'number', translation: 'nine', frequency: 'very_high' },
  { word: 'diez', pos: 'number', translation: 'ten', frequency: 'very_high' },
  { word: 'veinte', pos: 'number', translation: 'twenty', frequency: 'very_high' },
  { word: 'treinta', pos: 'number', translation: 'thirty', frequency: 'high' },
  { word: 'cien', pos: 'number', translation: 'hundred', frequency: 'very_high' },
  { word: 'mil', pos: 'number', translation: 'thousand', frequency: 'very_high' },
  
  // Common adverbs & prepositions
  { word: 'siempre', pos: 'adverb', translation: 'always', frequency: 'very_high' },
  { word: 'nunca', pos: 'adverb', translation: 'never', frequency: 'very_high' },
  { word: 'hoy', pos: 'adverb', translation: 'today', frequency: 'very_high' },
  { word: 'ayer', pos: 'adverb', translation: 'yesterday', frequency: 'very_high' },
  { word: 'mañana', pos: 'adverb', translation: 'tomorrow', frequency: 'very_high' },
  { word: 'ahora', pos: 'adverb', translation: 'now', frequency: 'very_high' },
  { word: 'luego', pos: 'adverb', translation: 'later/then', frequency: 'very_high' },
  { word: 'después', pos: 'adverb', translation: 'after/later', frequency: 'very_high' },
  { word: 'antes', pos: 'adverb', translation: 'before', frequency: 'very_high' },
  { word: 'aquí', pos: 'adverb', translation: 'here', frequency: 'very_high' },
  { word: 'allí', pos: 'adverb', translation: 'there', frequency: 'very_high' },
  { word: 'arriba', pos: 'adverb', translation: 'up/above', frequency: 'very_high' },
  { word: 'abajo', pos: 'adverb', translation: 'down/below', frequency: 'very_high' },
  { word: 'dentro', pos: 'adverb', translation: 'inside', frequency: 'very_high' },
  { word: 'fuera', pos: 'adverb', translation: 'outside', frequency: 'very_high' },
  { word: 'bien', pos: 'adverb', translation: 'well', frequency: 'very_high' },
  { word: 'mal', pos: 'adverb', translation: 'badly/wrong', frequency: 'very_high' },
  { word: 'casi', pos: 'adverb', translation: 'almost', frequency: 'very_high' },
  { word: 'bastante', pos: 'adverb', translation: 'quite/enough', frequency: 'very_high' },
  { word: 'demasiado', pos: 'adverb', translation: 'too much', frequency: 'very_high' },
  { word: 'juntos', pos: 'adverb', translation: 'together', frequency: 'very_high' },
  { word: 'solo', pos: 'adverb', translation: 'only/alone', frequency: 'very_high' },
  { word: 'también', pos: 'adverb', translation: 'also', frequency: 'very_high' },
  { word: 'tampoco', pos: 'adverb', translation: 'neither/either', frequency: 'very_high' },
  
  // Transportation & travel
  { word: 'coche', pos: 'noun', translation: 'car', frequency: 'very_high' },
  { word: 'auto', pos: 'noun', translation: 'car', frequency: 'very_high' },
  { word: 'autobús', pos: 'noun', translation: 'bus', frequency: 'high' },
  { word: 'tren', pos: 'noun', translation: 'train', frequency: 'very_high' },
  { word: 'avión', pos: 'noun', translation: 'airplane', frequency: 'very_high' },
  { word: 'barco', pos: 'noun', translation: 'boat/ship', frequency: 'high' },
  { word: 'bicicleta', pos: 'noun', translation: 'bicycle', frequency: 'high' },
  { word: 'camino', pos: 'noun', translation: 'path/way', frequency: 'very_high' },
  { word: 'carretera', pos: 'noun', translation: 'road/highway', frequency: 'high' },
  { word: 'viaje', pos: 'noun', translation: 'trip/journey', frequency: 'very_high' },
  
  // Technology & modern life
  { word: 'teléfono', pos: 'noun', translation: 'telephone', frequency: 'very_high' },
  { word: 'computadora', pos: 'noun', translation: 'computer', frequency: 'high' },
  { word: 'ordenador', pos: 'noun', translation: 'computer (Spain)', frequency: 'high' },
  { word: 'internet', pos: 'noun', translation: 'internet', frequency: 'very_high' },
  { word: 'correo', pos: 'noun', translation: 'mail/email', frequency: 'very_high' },
  { word: 'mensaje', pos: 'noun', translation: 'message', frequency: 'very_high' },
  { word: 'foto', pos: 'noun', translation: 'photo', frequency: 'very_high' },
  { word: 'película', pos: 'noun', translation: 'movie/film', frequency: 'very_high' },
  { word: 'televisión', pos: 'noun', translation: 'television', frequency: 'very_high' },
  { word: 'radio', pos: 'noun', translation: 'radio', frequency: 'very_high' },
  { word: 'periódico', pos: 'noun', translation: 'newspaper', frequency: 'high' },
  { word: 'revista', pos: 'noun', translation: 'magazine', frequency: 'high' },
  
  // Actions & movement
  { word: 'movimiento', pos: 'noun', translation: 'movement', frequency: 'very_high' },
  { word: 'paso', pos: 'noun', translation: 'step', frequency: 'very_high' },
  { word: 'salto', pos: 'noun', translation: 'jump', frequency: 'high' },
  { word: 'vuelta', pos: 'noun', translation: 'turn/return', frequency: 'very_high' },
  { word: 'golpe', pos: 'noun', translation: 'hit/blow', frequency: 'very_high' },
  { word: 'empujar', pos: 'verb', translation: 'to push', frequency: 'high' },
  { word: 'tirar', pos: 'verb', translation: 'to pull/throw', frequency: 'very_high' },
  { word: 'agarrar', pos: 'verb', translation: 'to grab', frequency: 'high' },
  { word: 'soltar', pos: 'verb', translation: 'to release/let go', frequency: 'high' },
  { word: 'sostener', pos: 'verb', translation: 'to hold/sustain', frequency: 'very_high' },
  
  // More verbs (200-300)
  { word: 'sentarse', pos: 'verb', translation: 'to sit down', frequency: 'very_high' },
  { word: 'levantarse', pos: 'verb', translation: 'to get up', frequency: 'very_high' },
  { word: 'dormir', pos: 'verb', translation: 'to sleep', frequency: 'very_high' },
  { word: 'despertar', pos: 'verb', translation: 'to wake up', frequency: 'very_high' },
  { word: 'comer', pos: 'verb', translation: 'to eat', frequency: 'very_high' },
  { word: 'beber', pos: 'verb', translation: 'to drink', frequency: 'very_high' },
  { word: 'cocinar', pos: 'verb', translation: 'to cook', frequency: 'high' },
  { word: 'limpiar', pos: 'verb', translation: 'to clean', frequency: 'high' },
  { word: 'lavar', pos: 'verb', translation: 'to wash', frequency: 'high' },
  { word: 'vestirse', pos: 'verb', translation: 'to get dressed', frequency: 'very_high' },
  { word: 'comprar', pos: 'verb', translation: 'to buy', frequency: 'very_high' },
  { word: 'vender', pos: 'verb', translation: 'to sell', frequency: 'very_high' },
  { word: 'preguntar', pos: 'verb', translation: 'to ask', frequency: 'very_high' },
  { word: 'contestar', pos: 'verb', translation: 'to answer', frequency: 'very_high' },
  { word: 'explicar', pos: 'verb', translation: 'to explain', frequency: 'very_high' },
  { word: 'enseñar', pos: 'verb', translation: 'to teach/show', frequency: 'very_high' },
  { word: 'aprender', pos: 'verb', translation: 'to learn', frequency: 'very_high' },
  { word: 'olvidar', pos: 'verb', translation: 'to forget', frequency: 'very_high' },
  { word: 'recordar', pos: 'verb', translation: 'to remember', frequency: 'very_high' },
  { word: 'reír', pos: 'verb', translation: 'to laugh', frequency: 'very_high' },
  { word: 'llorar', pos: 'verb', translation: 'to cry', frequency: 'very_high' },
  { word: 'sonreír', pos: 'verb', translation: 'to smile', frequency: 'very_high' },
  { word: 'gritar', pos: 'verb', translation: 'to shout', frequency: 'high' },
  { word: 'cantar', pos: 'verb', translation: 'to sing', frequency: 'very_high' },
  { word: 'bailar', pos: 'verb', translation: 'to dance', frequency: 'high' },
  { word: 'nadar', pos: 'verb', translation: 'to swim', frequency: 'high' },
  { word: 'viajar', pos: 'verb', translation: 'to travel', frequency: 'very_high' },
  { word: 'visitar', pos: 'verb', translation: 'to visit', frequency: 'very_high' },
  { word: 'regresar', pos: 'verb', translation: 'to return', frequency: 'very_high' },
  { word: 'enviar', pos: 'verb', translation: 'to send', frequency: 'very_high' },
  { word: 'recibir', pos: 'verb', translation: 'to receive', frequency: 'very_high' },
  { word: 'ganar', pos: 'verb', translation: 'to win/earn', frequency: 'very_high' },
  { word: 'perder', pos: 'verb', translation: 'to lose', frequency: 'very_high' },
  { word: 'amar', pos: 'verb', translation: 'to love', frequency: 'very_high' },
  { word: 'odiar', pos: 'verb', translation: 'to hate', frequency: 'high' },
  { word: 'esperar', pos: 'verb', translation: 'to wait/hope', frequency: 'very_high' },
  { word: 'desear', pos: 'verb', translation: 'to wish/desire', frequency: 'very_high' },
  { word: 'preferir', pos: 'verb', translation: 'to prefer', frequency: 'very_high' },
  { word: 'elegir', pos: 'verb', translation: 'to choose', frequency: 'very_high' },
  { word: 'decidir', pos: 'verb', translation: 'to decide', frequency: 'very_high' },
  { word: 'cambiar', pos: 'verb', translation: 'to change', frequency: 'very_high' },
  
  // More nouns - everyday objects
  { word: 'ropa', pos: 'noun', translation: 'clothes', frequency: 'very_high' },
  { word: 'camisa', pos: 'noun', translation: 'shirt', frequency: 'high' },
  { word: 'pantalón', pos: 'noun', translation: 'pants', frequency: 'high' },
  { word: 'zapato', pos: 'noun', translation: 'shoe', frequency: 'very_high' },
  { word: 'sombrero', pos: 'noun', translation: 'hat', frequency: 'high' },
  { word: 'reloj', pos: 'noun', translation: 'watch/clock', frequency: 'very_high' },
  { word: 'dinero', pos: 'noun', translation: 'money', frequency: 'very_high' },
  { word: 'precio', pos: 'noun', translation: 'price', frequency: 'very_high' },
  { word: 'compra', pos: 'noun', translation: 'purchase', frequency: 'high' },
  { word: 'venta', pos: 'noun', translation: 'sale', frequency: 'high' },
  { word: 'cuenta', pos: 'noun', translation: 'bill/account', frequency: 'very_high' },
  { word: 'tarjeta', pos: 'noun', translation: 'card', frequency: 'very_high' },
  { word: 'llave', pos: 'noun', translation: 'key', frequency: 'very_high' },
  { word: 'bolso', pos: 'noun', translation: 'bag/purse', frequency: 'high' },
  { word: 'bolsillo', pos: 'noun', translation: 'pocket', frequency: 'high' },
  { word: 'paraguas', pos: 'noun', translation: 'umbrella', frequency: 'medium' },
  { word: 'gafas', pos: 'noun', translation: 'glasses', frequency: 'high' },
  
  // Work & education
  { word: 'trabajo', pos: 'noun', translation: 'work/job', frequency: 'very_high' },
  { word: 'empleado', pos: 'noun', translation: 'employee', frequency: 'high' },
  { word: 'jefe', pos: 'noun', translation: 'boss', frequency: 'very_high' },
  { word: 'empresa', pos: 'noun', translation: 'company', frequency: 'very_high' },
  { word: 'negocio', pos: 'noun', translation: 'business', frequency: 'very_high' },
  { word: 'reunión', pos: 'noun', translation: 'meeting', frequency: 'very_high' },
  { word: 'proyecto', pos: 'noun', translation: 'project', frequency: 'very_high' },
  { word: 'escuela', pos: 'noun', translation: 'school', frequency: 'very_high' },
  { word: 'universidad', pos: 'noun', translation: 'university', frequency: 'very_high' },
  { word: 'clase', pos: 'noun', translation: 'class', frequency: 'very_high' },
  { word: 'estudiante', pos: 'noun', translation: 'student', frequency: 'very_high' },
  { word: 'profesor', pos: 'noun', translation: 'teacher/professor', frequency: 'very_high' },
  { word: 'maestro', pos: 'noun', translation: 'teacher/master', frequency: 'very_high' },
  { word: 'alumno', pos: 'noun', translation: 'pupil/student', frequency: 'high' },
  { word: 'examen', pos: 'noun', translation: 'exam', frequency: 'very_high' },
  { word: 'tarea', pos: 'noun', translation: 'homework/task', frequency: 'very_high' },
  { word: 'pregunta', pos: 'noun', translation: 'question', frequency: 'very_high' },
  { word: 'respuesta', pos: 'noun', translation: 'answer', frequency: 'very_high' },
  { word: 'conocimiento', pos: 'noun', translation: 'knowledge', frequency: 'very_high' },
  
  // Emotions & states
  { word: 'felicidad', pos: 'noun', translation: 'happiness', frequency: 'high' },
  { word: 'dolor', pos: 'noun', translation: 'pain', frequency: 'very_high' },
  { word: 'placer', pos: 'noun', translation: 'pleasure', frequency: 'high' },
  { word: 'sorpresa', pos: 'noun', translation: 'surprise', frequency: 'very_high' },
  { word: 'duda', pos: 'noun', translation: 'doubt', frequency: 'very_high' },
  { word: 'confianza', pos: 'noun', translation: 'confidence/trust', frequency: 'very_high' },
  { word: 'paciencia', pos: 'noun', translation: 'patience', frequency: 'high' },
  { word: 'valentía', pos: 'noun', translation: 'courage', frequency: 'high' },
  { word: 'vergüenza', pos: 'noun', translation: 'shame', frequency: 'high' },
  { word: 'orgullo', pos: 'noun', translation: 'pride', frequency: 'high' },
  { word: 'celos', pos: 'noun', translation: 'jealousy', frequency: 'high' },
  { word: 'envidia', pos: 'noun', translation: 'envy', frequency: 'high' },
  { word: 'rabia', pos: 'noun', translation: 'rage', frequency: 'high' },
  { word: 'calma', pos: 'noun', translation: 'calm', frequency: 'very_high' },
  
  // More common verbs
  { word: 'mostrar', pos: 'verb', translation: 'to show', frequency: 'very_high' },
  { word: 'demostrar', pos: 'verb', translation: 'to demonstrate', frequency: 'very_high' },
  { word: 'probar', pos: 'verb', translation: 'to try/prove', frequency: 'very_high' },
  { word: 'mejorar', pos: 'verb', translation: 'to improve', frequency: 'very_high' },
  { word: 'empeorar', pos: 'verb', translation: 'to worsen', frequency: 'high' },
  { word: 'aumentar', pos: 'verb', translation: 'to increase', frequency: 'very_high' },
  { word: 'disminuir', pos: 'verb', translation: 'to decrease', frequency: 'high' },
  { word: 'reducir', pos: 'verb', translation: 'to reduce', frequency: 'very_high' },
  { word: 'evitar', pos: 'verb', translation: 'to avoid', frequency: 'very_high' },
  { word: 'impedir', pos: 'verb', translation: 'to prevent', frequency: 'very_high' },
  { word: 'suponer', pos: 'verb', translation: 'to suppose', frequency: 'very_high' },
  { word: 'proponer', pos: 'verb', translation: 'to propose', frequency: 'very_high' },
  { word: 'comprender', pos: 'verb', translation: 'to understand', frequency: 'very_high' },
  { word: 'incluir', pos: 'verb', translation: 'to include', frequency: 'very_high' },
  { word: 'excluir', pos: 'verb', translation: 'to exclude', frequency: 'high' },
  { word: 'contener', pos: 'verb', translation: 'to contain', frequency: 'very_high' },
  { word: 'obtener', pos: 'verb', translation: 'to obtain', frequency: 'very_high' },
  { word: 'sostener', pos: 'verb', translation: 'to sustain/hold', frequency: 'very_high' },
  { word: 'detener', pos: 'verb', translation: 'to stop/detain', frequency: 'very_high' },
  { word: 'continuar', pos: 'verb', translation: 'to continue', frequency: 'very_high' },
  { word: 'terminar', pos: 'verb', translation: 'to finish', frequency: 'very_high' },
  { word: 'completar', pos: 'verb', translation: 'to complete', frequency: 'high' },
  { word: 'organizar', pos: 'verb', translation: 'to organize', frequency: 'very_high' },
  { word: 'preparar', pos: 'verb', translation: 'to prepare', frequency: 'very_high' },
  { word: 'planear', pos: 'verb', translation: 'to plan', frequency: 'high' },
  { word: 'arreglar', pos: 'verb', translation: 'to fix/arrange', frequency: 'very_high' },
  { word: 'romper', pos: 'verb', translation: 'to break', frequency: 'very_high' },
  { word: 'construir', pos: 'verb', translation: 'to build', frequency: 'very_high' },
  { word: 'destruir', pos: 'verb', translation: 'to destroy', frequency: 'very_high' },
  { word: 'pintar', pos: 'verb', translation: 'to paint', frequency: 'high' },
  { word: 'dibujar', pos: 'verb', translation: 'to draw', frequency: 'high' },
  { word: 'escribir', pos: 'verb', translation: 'to write', frequency: 'very_high' },
  { word: 'firmar', pos: 'verb', translation: 'to sign', frequency: 'very_high' },
  { word: 'borrar', pos: 'verb', translation: 'to erase', frequency: 'high' },
  { word: 'cortar', pos: 'verb', translation: 'to cut', frequency: 'very_high' },
  { word: 'pegar', pos: 'verb', translation: 'to glue/hit', frequency: 'high' },
  { word: 'cerrar', pos: 'verb', translation: 'to close', frequency: 'very_high' },
  { word: 'abrir', pos: 'verb', translation: 'to open', frequency: 'very_high' },
  { word: 'cerrar', pos: 'verb', translation: 'to close', frequency: 'very_high' },
  { word: 'empujar', pos: 'verb', translation: 'to push', frequency: 'high' },
  { word: 'jalar', pos: 'verb', translation: 'to pull', frequency: 'high' },
  
  // More common nouns
  { word: 'chico', pos: 'noun', translation: 'boy', frequency: 'very_high' },
  { word: 'chica', pos: 'noun', translation: 'girl', frequency: 'very_high' },
  { word: 'señora', pos: 'noun', translation: 'lady/Mrs.', frequency: 'very_high' },
  { word: 'señorita', pos: 'noun', translation: 'young lady/Miss', frequency: 'high' },
  { word: 'doctor', pos: 'noun', translation: 'doctor', frequency: 'very_high' },
  { word: 'enfermero', pos: 'noun', translation: 'nurse', frequency: 'high' },
  { word: 'médico', pos: 'noun', translation: 'doctor/physician', frequency: 'very_high' },
  { word: 'policía', pos: 'noun', translation: 'police', frequency: 'very_high' },
  { word: 'soldado', pos: 'noun', translation: 'soldier', frequency: 'high' },
  { word: 'abogado', pos: 'noun', translation: 'lawyer', frequency: 'very_high' },
  { word: 'ingeniero', pos: 'noun', translation: 'engineer', frequency: 'high' },
  { word: 'artista', pos: 'noun', translation: 'artist', frequency: 'very_high' },
  { word: 'escritor', pos: 'noun', translation: 'writer', frequency: 'very_high' },
  { word: 'músico', pos: 'noun', translation: 'musician', frequency: 'high' },
  { word: 'actor', pos: 'noun', translation: 'actor', frequency: 'very_high' },
  { word: 'cantante', pos: 'noun', translation: 'singer', frequency: 'high' },
  { word: 'cocinero', pos: 'noun', translation: 'cook/chef', frequency: 'high' },
  { word: 'camarero', pos: 'noun', translation: 'waiter', frequency: 'high' },
  { word: 'cliente', pos: 'noun', translation: 'client/customer', frequency: 'very_high' },
  { word: 'vecino', pos: 'noun', translation: 'neighbor', frequency: 'very_high' },
  { word: 'dueño', pos: 'noun', translation: 'owner', frequency: 'very_high' },
  { word: 'jefe', pos: 'noun', translation: 'boss/chief', frequency: 'very_high' },
  
  // Animals
  { word: 'perro', pos: 'noun', translation: 'dog', frequency: 'very_high' },
  { word: 'gato', pos: 'noun', translation: 'cat', frequency: 'very_high' },
  { word: 'pájaro', pos: 'noun', translation: 'bird', frequency: 'very_high' },
  { word: 'caballo', pos: 'noun', translation: 'horse', frequency: 'very_high' },
  { word: 'vaca', pos: 'noun', translation: 'cow', frequency: 'high' },
  { word: 'cerdo', pos: 'noun', translation: 'pig', frequency: 'high' },
  { word: 'oveja', pos: 'noun', translation: 'sheep', frequency: 'high' },
  { word: 'pez', pos: 'noun', translation: 'fish', frequency: 'high' },
  { word: 'león', pos: 'noun', translation: 'lion', frequency: 'high' },
  { word: 'tigre', pos: 'noun', translation: 'tiger', frequency: 'high' },
  { word: 'oso', pos: 'noun', translation: 'bear', frequency: 'high' },
  { word: 'ratón', pos: 'noun', translation: 'mouse', frequency: 'high' },
  { word: 'mosquito', pos: 'noun', translation: 'mosquito', frequency: 'medium' },
  { word: 'abeja', pos: 'noun', translation: 'bee', frequency: 'medium' },
  { word: 'araña', pos: 'noun', translation: 'spider', frequency: 'high' },
  { word: 'serpiente', pos: 'noun', translation: 'snake', frequency: 'high' },
  
  // Time expressions
  { word: 'momento', pos: 'noun', translation: 'moment', frequency: 'very_high' },
  { word: 'hora', pos: 'noun', translation: 'hour', frequency: 'very_high' },
  { word: 'minuto', pos: 'noun', translation: 'minute', frequency: 'very_high' },
  { word: 'segundo', pos: 'noun', translation: 'second', frequency: 'very_high' },
  { word: 'semana', pos: 'noun', translation: 'week', frequency: 'very_high' },
  { word: 'mes', pos: 'noun', translation: 'month', frequency: 'very_high' },
  { word: 'año', pos: 'noun', translation: 'year', frequency: 'very_high' },
  { word: 'siglo', pos: 'noun', translation: 'century', frequency: 'very_high' },
  { word: 'época', pos: 'noun', translation: 'era/time period', frequency: 'very_high' },
  { word: 'fecha', pos: 'noun', translation: 'date', frequency: 'very_high' },
  { word: 'mañana', pos: 'noun', translation: 'tomorrow/morning', frequency: 'very_high' },
  { word: 'tarde', pos: 'noun', translation: 'afternoon/late', frequency: 'very_high' },
  { word: 'noche', pos: 'noun', translation: 'night', frequency: 'very_high' },
  { word: 'madrugada', pos: 'noun', translation: 'dawn/early morning', frequency: 'high' },
  { word: 'mediodía', pos: 'noun', translation: 'noon/midday', frequency: 'high' },
  { word: 'medianoche', pos: 'noun', translation: 'midnight', frequency: 'high' },
  
  // More common adjectives
  { word: 'listo', pos: 'adjective', translation: 'ready/smart', frequency: 'very_high' },
  { word: 'tonto', pos: 'adjective', translation: 'silly/dumb', frequency: 'high' },
  { word: 'inteligente', pos: 'adjective', translation: 'intelligent', frequency: 'very_high' },
  { word: 'amable', pos: 'adjective', translation: 'kind/nice', frequency: 'very_high' },
  { word: 'cruel', pos: 'adjective', translation: 'cruel', frequency: 'high' },
  { word: 'generoso', pos: 'adjective', translation: 'generous', frequency: 'high' },
  { word: 'egoísta', pos: 'adjective', translation: 'selfish', frequency: 'high' },
  { word: 'honesto', pos: 'adjective', translation: 'honest', frequency: 'high' },
  { word: 'mentiroso', pos: 'adjective', translation: 'liar/lying', frequency: 'high' },
  { word: 'valiente', pos: 'adjective', translation: 'brave', frequency: 'high' },
  { word: 'cobarde', pos: 'adjective', translation: 'coward', frequency: 'high' },
  { word: 'educado', pos: 'adjective', translation: 'polite/educated', frequency: 'high' },
  { word: 'grosero', pos: 'adjective', translation: 'rude', frequency: 'high' },
  { word: 'tranquilo', pos: 'adjective', translation: 'calm/quiet', frequency: 'very_high' },
  { word: 'nervioso', pos: 'adjective', translation: 'nervous', frequency: 'very_high' },
  { word: 'cansado', pos: 'adjective', translation: 'tired', frequency: 'very_high' },
  { word: 'aburrido', pos: 'adjective', translation: 'bored/boring', frequency: 'very_high' },
  { word: 'interesante', pos: 'adjective', translation: 'interesting', frequency: 'very_high' },
  { word: 'divertido', pos: 'adjective', translation: 'fun/funny', frequency: 'very_high' },
  { word: 'serio', pos: 'adjective', translation: 'serious', frequency: 'very_high' },
  { word: 'raro', pos: 'adjective', translation: 'strange/rare', frequency: 'very_high' },
  { word: 'normal', pos: 'adjective', translation: 'normal', frequency: 'very_high' },
  { word: 'especial', pos: 'adjective', translation: 'special', frequency: 'very_high' },
  { word: 'común', pos: 'adjective', translation: 'common', frequency: 'very_high' },
  { word: 'diferente', pos: 'adjective', translation: 'different', frequency: 'very_high' },
  { word: 'igual', pos: 'adjective', translation: 'equal/same', frequency: 'very_high' },
  { word: 'similar', pos: 'adjective', translation: 'similar', frequency: 'very_high' },
  { word: 'distinto', pos: 'adjective', translation: 'distinct/different', frequency: 'very_high' },
  { word: 'único', pos: 'adjective', translation: 'unique/only', frequency: 'very_high' },
  { word: 'varios', pos: 'adjective', translation: 'several', frequency: 'very_high' },
  { word: 'ambos', pos: 'adjective', translation: 'both', frequency: 'very_high' },
  { word: 'cada', pos: 'adjective', translation: 'each', frequency: 'very_high' },
  { word: 'todo', pos: 'adjective', translation: 'all/every', frequency: 'very_high' },
  { word: 'alguno', pos: 'adjective', translation: 'some', frequency: 'very_high' },
  { word: 'ninguno', pos: 'adjective', translation: 'none', frequency: 'very_high' },
  
  // More locations
  { word: 'aeropuerto', pos: 'noun', translation: 'airport', frequency: 'high' },
  { word: 'estación', pos: 'noun', translation: 'station', frequency: 'very_high' },
  { word: 'parada', pos: 'noun', translation: 'stop', frequency: 'high' },
  { word: 'esquina', pos: 'noun', translation: 'corner', frequency: 'high' },
  { word: 'centro', pos: 'noun', translation: 'center/downtown', frequency: 'very_high' },
  { word: 'plaza', pos: 'noun', translation: 'square/plaza', frequency: 'very_high' },
  { word: 'parque', pos: 'noun', translation: 'park', frequency: 'very_high' },
  { word: 'jardín', pos: 'noun', translation: 'garden', frequency: 'very_high' },
  { word: 'cine', pos: 'noun', translation: 'cinema/movie theater', frequency: 'very_high' },
  { word: 'teatro', pos: 'noun', translation: 'theater', frequency: 'very_high' },
  { word: 'museo', pos: 'noun', translation: 'museum', frequency: 'very_high' },
  { word: 'biblioteca', pos: 'noun', translation: 'library', frequency: 'very_high' },
  { word: 'gimnasio', pos: 'noun', translation: 'gym', frequency: 'high' },
  { word: 'estadio', pos: 'noun', translation: 'stadium', frequency: 'high' },
  { word: 'piscina', pos: 'noun', translation: 'swimming pool', frequency: 'high' },
  
  // Weather & seasons
  { word: 'tiempo', pos: 'noun', translation: 'time/weather', frequency: 'very_high' },
  { word: 'clima', pos: 'noun', translation: 'climate', frequency: 'high' },
  { word: 'temperatura', pos: 'noun', translation: 'temperature', frequency: 'high' },
  { word: 'calor', pos: 'noun', translation: 'heat', frequency: 'very_high' },
  { word: 'frío', pos: 'noun', translation: 'cold', frequency: 'very_high' },
  { word: 'primavera', pos: 'noun', translation: 'spring', frequency: 'very_high' },
  { word: 'verano', pos: 'noun', translation: 'summer', frequency: 'very_high' },
  { word: 'otoño', pos: 'noun', translation: 'autumn/fall', frequency: 'very_high' },
  { word: 'invierno', pos: 'noun', translation: 'winter', frequency: 'very_high' },
  
  // Technology & communication
  { word: 'carta', pos: 'noun', translation: 'letter', frequency: 'very_high' },
  { word: 'palabra', pos: 'noun', translation: 'word', frequency: 'very_high' },
  { word: 'frase', pos: 'noun', translation: 'sentence/phrase', frequency: 'very_high' },
  { word: 'idioma', pos: 'noun', translation: 'language', frequency: 'very_high' },
  { word: 'acento', pos: 'noun', translation: 'accent', frequency: 'high' },
  { word: 'conversación', pos: 'noun', translation: 'conversation', frequency: 'very_high' },
  { word: 'discusión', pos: 'noun', translation: 'discussion/argument', frequency: 'high' },
  { word: 'llamada', pos: 'noun', translation: 'call', frequency: 'very_high' },
  { word: 'noticia', pos: 'noun', translation: 'news', frequency: 'very_high' },
  { word: 'información', pos: 'noun', translation: 'information', frequency: 'very_high' },
  
  // Household items
  { word: 'cosa', pos: 'noun', translation: 'thing', frequency: 'very_high' },
  { word: 'objeto', pos: 'noun', translation: 'object', frequency: 'very_high' },
  { word: 'botella', pos: 'noun', translation: 'bottle', frequency: 'high' },
  { word: 'vaso', pos: 'noun', translation: 'glass', frequency: 'very_high' },
  { word: 'taza', pos: 'noun', translation: 'cup/mug', frequency: 'high' },
  { word: 'plato', pos: 'noun', translation: 'plate/dish', frequency: 'very_high' },
  { word: 'cuchillo', pos: 'noun', translation: 'knife', frequency: 'high' },
  { word: 'tenedor', pos: 'noun', translation: 'fork', frequency: 'high' },
  { word: 'cuchara', pos: 'noun', translation: 'spoon', frequency: 'high' },
  { word: 'servilleta', pos: 'noun', translation: 'napkin', frequency: 'medium' },
  { word: 'toalla', pos: 'noun', translation: 'towel', frequency: 'high' },
  { word: 'jabón', pos: 'noun', translation: 'soap', frequency: 'high' },
  { word: 'espejo', pos: 'noun', translation: 'mirror', frequency: 'very_high' },
  { word: 'lámpara', pos: 'noun', translation: 'lamp', frequency: 'high' },
  { word: 'almohada', pos: 'noun', translation: 'pillow', frequency: 'high' },
  { word: 'manta', pos: 'noun', translation: 'blanket', frequency: 'high' },
  { word: 'sábana', pos: 'noun', translation: 'sheet', frequency: 'high' },
  
  // More verbs for variety
  { word: 'mirar', pos: 'verb', translation: 'to look at', frequency: 'very_high' },
  { word: 'observar', pos: 'verb', translation: 'to observe', frequency: 'very_high' },
  { word: 'notar', pos: 'verb', translation: 'to notice', frequency: 'very_high' },
  { word: 'encontrar', pos: 'verb', translation: 'to find', frequency: 'very_high' },
  { word: 'buscar', pos: 'verb', translation: 'to search', frequency: 'very_high' },
  { word: 'perder', pos: 'verb', translation: 'to lose', frequency: 'very_high' },
  { word: 'guardar', pos: 'verb', translation: 'to keep/save', frequency: 'very_high' },
  { word: 'tirar', pos: 'verb', translation: 'to throw away', frequency: 'very_high' },
  { word: 'recoger', pos: 'verb', translation: 'to pick up/collect', frequency: 'very_high' },
  { word: 'dejar', pos: 'verb', translation: 'to leave/let', frequency: 'very_high' },
  { word: 'traer', pos: 'verb', translation: 'to bring', frequency: 'very_high' },
  { word: 'llevar', pos: 'verb', translation: 'to carry/take', frequency: 'very_high' },
  { word: 'mover', pos: 'verb', translation: 'to move', frequency: 'very_high' },
  { word: 'parar', pos: 'verb', translation: 'to stop', frequency: 'very_high' },
  { word: 'quedar', pos: 'verb', translation: 'to stay/remain', frequency: 'very_high' },
  { word: 'sentar', pos: 'verb', translation: 'to sit/seat', frequency: 'very_high' },
  { word: 'acostar', pos: 'verb', translation: 'to put to bed', frequency: 'high' },
  { word: 'despertar', pos: 'verb', translation: 'to wake up', frequency: 'very_high' },
];

async function main() {
  console.log('📚 Expanding Word List\n');
  
  // Load existing list
  const data = JSON.parse(fs.readFileSync(WORDS_FILE, 'utf-8'));
  const existingWords = new Set(data.words.map((w: any) => w.word.toLowerCase()));
  
  console.log(`Current words: ${data.words.length}`);
  console.log(`Additional words available: ${additionalWords.length}`);
  
  // Add new words (avoid duplicates)
  let added = 0;
  let currentRank = data.words.length + 1;
  
  for (const word of additionalWords) {
    if (!existingWords.has(word.word.toLowerCase())) {
      data.words.push({
        rank: currentRank++,
        ...word,
      });
      added++;
    }
  }
  
  // Update metadata
  data.metadata.totalWords = data.words.length;
  data.metadata.lastUpdated = new Date().toISOString();
  
  // Save
  fs.writeFileSync(WORDS_FILE, JSON.stringify(data, null, 2));
  
  console.log(`\n✅ Word list expanded!`);
  console.log(`   Added: ${added} words`);
  console.log(`   Total: ${data.words.length} words`);
  console.log(`   File: ${WORDS_FILE}\n`);
}

main().catch(console.error);
